modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    logoFile = "logo.png"
    authors = "${mod_author}"
    description = "${mod_description}"
    credits = "ToroCraft, Lynzl"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    mandatory = true
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "${side}"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "${side}"

[[mixins]]
    config = "${mod_id}.mixins.json"
